### ISSUE TITLE
document recommended approach to deploy with Gitlab

### ISSUE THREAD

**Issue by h0uter** [likec4/likec4#1194]
Awesome tool!

Currently, [the docs show how to deploy with github actions](https://likec4.dev/tooling/github/), what would be the recommended approach for deploying with Gitlab and `.gitlab-ci.yml`?

**Comment by h0uter** [comment]
I found the following snippet `gitlab-ci.yml` works for me:


```yaml
image: node:22

# Job for releasing documentation on Gitlab Pages.
pages:
  script:
    - npx likec4 build -o site . 
  artifacts:
    paths:
      - site
  publish: site # Which local directory Gitlab can find your site html
```

**Comment by jentor** [comment]
@h0uter 
As a first-timer in gitlab pipeline writing that is what working for me:

`.gitlab-ci.yml`
```yaml
docker-build:
  image: docker:latest
  stage: build
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd likec4 # 🟡 my folder with all of 'likec4' stuff (like Dockerfile) one step down from root /
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
        docker push "$CI_REGISTRY_IMAGE:latest"
      fi
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
```

`Dockerfile`
```
FROM node:alpine AS build
RUN npm install --global likec4
# 🟡 Note that you may need to change this folder, cause in my case all .c4 files in /likec4/arch-model
COPY ./arch-model /source/
RUN likec4 build --use-hash-history -o /dist /source

FROM nginx:stable-alpine
COPY --from=build /dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by h0uter** [comment]
Due to errors with the `dot` binary, I had to update my `.gitlab-ci.yml` file to:


```yaml
# Job for releasing documentation on Gitlab Pages.
pages:
  image:
    name: ghcr.io/likec4/likec4
    entrypoint: [""]
  script:
    - likec4 build src --output site --title "System Architecture"
  artifacts:
    paths:
      - site
  publish: site # Which local directory Gitlab can find your site html
```

Note: this is for a private Gitlab organisation with Gitlab pages setup.
